### ISSUE TITLE
<leader> m is undefined

### ISSUE THREAD

**Issue by delexi** [syl20bnr/evil-lisp-state#7]
I installed this package via MELPA and put the following into my init file:
```elisp
  (use-package evil-lisp-state :ensure t ;; :pin melpa-stable
    :pre-load
    (progn
      (setq evil-lisp-state-major-modes
            '(emacs-lisp-mode
              clojure-mode
              common-lisp-mode))))
```
When I am in an emacs-lisp-mode buffer and press \<leader\> m, emacs echos "\<leader\> m is undefined".

Did I do something wrong while installing?

**Comment by tuhdo** [comment]
@syl20bnr  I have this issue as well. Probably it is only setup for Spacemacs?

**Comment by tuhdo** [comment]
@delexi I found out how to set it up properly thanks to Spacemacs:

```elisp
(setq evil-lisp-state-global t)
(setq evil-lisp-state-leader-prefix "m")
(require 'evil-lisp-state)
```

Documentation should be updated.

**Comment by syl20bnr** [comment]
@delexi I tried with the last use-package and `<leader> m` was available in emacs lisp:

  (use-package evil-lisp-state
    :preface
    (progn
      (setq evil-lisp-state-major-modes
            '(emacs-lisp-mode
              clojure-mode
              common-lisp-mode))))

Maybe the correct <leader> key was not yet defined in your setup when evil-lisp-state was evaluated ?

**Comment by delexi** [comment]
@syl20bnr I used :init now and everything works as expected!
