### ISSUE TITLE
Forward/backward/up sexp

### ISSUE THREAD

**Issue by jcpetkovich** [syl20bnr/evil-lisp-state#9]
Moving around by sexp is something that's pretty useful, but it isn't currently bound to keys in this state.

I have been playing around with bindings like:

    (bind-keys :map evil-lisp-state-map
               ("U" . sp-backward-up-sexp)
               ("L" . sp-forward-sexp)
               ("H" . sp-backward-sexp))

And they work quite nicely. Any thoughts on including these? Or on what keys they should be bound?

**Comment by syl20bnr** [comment]
Thank you, I added them :+1:
